version: '3'

services: 

  publisher_app:
    build: 
      context: .
      dockerfile: ./publisher/publisher.dockerfile
    container_name: publisher
    ports: 
      - 8000:8000
    volumes: 
      - ./publisher:/usr/src/app/publisher
    depends_on:
      - publisher-redis-server
    networks: 
      - notification-network

  publisher-redis-server:
    image: redis:6.0.12-alpine
    container_name: publisher_redis
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379
    volumes:
      - ./publisher/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./publisher/redisdata:/usr/local/etc/redis
    networks: 
      - notification-network

  subscriber_app:
    build: 
      context: .
      dockerfile: ./subscriber/subscriber.dockerfile
    container_name: subscriber
    ports: 
      - 8080:8080
    volumes: 
      - ./subscriber:/usr/src/app/subscriber
    depends_on:
      - subscriber-redis-server
    networks: 
      - notification-network

  subscriber-redis-server:
    image: redis:6.0.12-alpine
    container_name: subscriber_redis
    restart: unless-stopped
    tty: true
    ports:
      - 6389:6379
    volumes:
      - ./subscriber/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./subscriber/redisdata:/usr/local/etc/redis
    networks: 
      - notification-network

networks: 
  notification-network:
    driver: bridge